name: CI
on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Test
        run: python -m setup.py nosetests
